### ISSUE TITLE
release RANN1 to CRAN

### ISSUE THREAD

**Issue by jefferis** [jefferis/RANN#13]
RANN1 (by @krlmlr on top of the original RANN) supports the Manhattan (L1) norm rather than the standard Euclidean (L2) metric. It should be pretty much for release to CRAN – and I propose that he is the maintainer! Presumably the version numbers should be kept in sync as much as possible.

**Comment by krlmlr** [comment]
Thanks, that's fine with me. Please ping me when `RANN` is on CRAN.

**Comment by jefferis** [comment]
On 14 Apr 2015, at 21:08, Kirill Müller <notifications@github.com> wrote:

> Thanks, that's fine with me. Please ping me when RANN is on CRAN.
> 

Sure, but I think you can go ahead and submit RANN1 without waiting. Best,

Greg.

**Comment by krlmlr** [comment]
I think version numbers should be kept in sync, and I'd rather merge your released version into `master-L1` before starting any funny business... CRAN should happen eventually (preferably before June), but no need to hurry.

**Comment by jefferis** [comment]
Hi @krlmlr, Just to let you know that RANN 2.5 is on CRAN now. I guess it may take a day or two for binaries to build etc.

**Comment by krlmlr** [comment]
Released.

**Comment by jefferis** [comment]
Great!
