### ISSUE TITLE
Please ship declarations in inst/include so we can linkingTo your c++ functions 

### ISSUE THREAD

**Issue by caiohamamura** [jefferis/RANN#27]
Hi @jefferis, it would be great if your c++ functions were exported by adding `// [[Rcpp::interfaces(r, cpp)]]` to the relevant c++ functions for using your indexing methods.

I've already used those in my projects because it uses one of the fastest implementations of indexing, but currently I'm just copying your code and using it my personal projects.

Thanks a lot!

**Comment by jefferis** [comment]
Thanks. I’m pretty busy at the moment, but I’m open to PRs. That said, this package doesn’t use RCpp at the moment but there’s a more modern interface in the RANN2 package.

**Comment by jefferis** [comment]
Can I just check that your RANN2 PR (https://github.com/jefferis/RANN2/pull/2) covers this? If so please close this issue.
