### ISSUE TITLE
ANN library version mismatch in documentation

### ISSUE THREAD

**Issue by jondo** [jefferis/RANN#34]
The doc page https://jefferislab.github.io/RANN/ says that v1.1.3 of the ANN library is wrapped, while https://www.cs.umd.edu/~mount/ANN/ currently only provides version 1.1.2.

Is this a typo?

**Comment by jefferis** [comment]
It's a fair question but it's not a typo. The v1.1.3 sources from David Mount although it appears he never released them publicly. See commit message for https://github.com/jefferislab/RANN/commit/ceec702304bbbf2be10f333b42362368ad400be9
